const SMALL_BREAKPOINT = "375px";
const TABLET_BREAKPOINT = "768px";
const DESKTOP_BREAKPOINT = "1366px";
const TW_SM_BREAKPOINT = "640px";

export const cssBreakPoints = {
  SMALL_BREAKPOINT,
  TABLET_BREAKPOINT,
  DESKTOP_BREAKPOINT,
  TW_SM_BREAKPOINT,
};
